version: '2.27.0'
services:
  elasticsearch:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3



  food-ease:
    image: appv4
    build: .
    ports:
      - 5454:5454
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
