FROM openjdk:19


EXPOSE 5454

ADD target/Online_Food_Ordering_System-0.0.1-SNAPSHOT.jar Online_Food_Ordering_System-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "Online_Food_Ordering_System-0.0.1-SNAPSHOT.jar"]